# Site settings
title: pggsnap's blog
SEOTitle: pggsnap的博客
header-img: img/home-bg.jpg
email: pggsnap@gmail.com
description: ""
keyword: ""
url: "https://pggsnap.github.io"

# SNS settings
RSS: false
github_username: pggsnap

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
disqus_username: pggsnap

# Google Analytics
ga_track_id: 'UA-114920300-1'            # Format: UA-xxxxxx-xx
ga_domain: pggsnap.github.io

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "记录、整理一些文档"
sidebar-avatar:      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
